id = "railscast-zed"
name = "railscast-zed"
version = "0.1.0"
schema_version = 1
authors = [
    "Peder Bergebakken Sundt <pbsds@hotmail.com>",
]
description = "A colorscheme based on the TextMate theme."
repository = "https://github.com/pbsds/railscast-zed"
